### ISSUE TITLE
Word lists

### ISSUE THREAD

**Issue by smeisler** [BarbaraMath/Lexical_Decision_Task#1]
Hi,

Do you plan on releasing the word lists you used?

Thanks,
Steven

**Comment by BarbaraMath** [comment]
Hi Steven,

Thank you for reaching out! Unfortunately this was part of a post-graduate course, and it is not a published paper (then we would share all stimuli). 
However, we generated our pseudowords very easily through the Multilingual Pseudoword Generator ''Wuggy'' (http://crr.ugent.be/programs-data/wuggy) and also got inspiration for our stimuli from White, H. (1986). Semantic priming of nonwords in lexical decision. The American journal of psychology, 479-485.

I hope it helps!

Kind regards,
Barbara.

**Comment by smeisler** [comment]
Hi Barbara,

Understood, thank you!
